# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr: none
trigger: none

pool:
  vmImage: 'windows-2019'

variables:
  Codeql.Enabled: true
  BuildConfiguration: 'Release'
  solution: 'apidoctools.sln'
  buildPlatform: 'Any CPU'
  
steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet Tool

- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

